<<<<<<< HEAD
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "http://localhost:3001";
export const API_BASE =
  import.meta.env.VITE_API_BASE || "http://localhost:3001/make-server-21f56fa4";
=======
export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID ?? "";

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";

export const API_BASE = import.meta.env.VITE_API_BASE ?? "";
>>>>>>> ff40e0f079c428a1ab1e18f6e586876db6206689
