/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://webtest-backend.onrender.com";
export const API_BASE =
  import.meta.env.VITE_API_BASE || "https://webtest-backend.onrender.com/make-server-21f56fa4";
